# Generated by Django 2.2.1 on 2019-05-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RacingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.DateTimeField(verbose_name='Starting time')),
                ('ending_time', models.DateTimeField(verbose_name='Ending time')),
                ('successes', models.PositiveIntegerField(verbose_name='2xx')),
                ('redirects', models.PositiveIntegerField(verbose_name='3xx')),
                ('soft_errors', models.PositiveIntegerField(verbose_name='4xx')),
                ('hard_errors', models.PositiveIntegerField(verbose_name='5xx')),
                ('crawled', models.PositiveIntegerField(verbose_name='Crawled')),
            ],
        ),
        migrations.CreateModel(
            name='RacingResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RacingSession')),
            ],
        ),
    ]
