# Generated by Django 2.2.1 on 2019-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racingsession',
            name='base_url',
            field=models.CharField(default='http://localhost:555/', max_length=512, verbose_name='Starting point'),
            preserve_default=False,
        ),
    ]
